// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0fFdANieqCpKUZQ7XEDFrl7-1dSjiigM',
    appId: '1:904470300360:web:84cb8ccc48969d33f907fd',
    messagingSenderId: '904470300360',
    projectId: 'gerak-34866',
    authDomain: 'gerak-34866.firebaseapp.com',
    storageBucket: 'gerak-34866.firebasestorage.app',
    measurementId: 'G-EECBH1R7E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxh6CdARYsNA-GFiDLMtn5FXPTwOFXxTM',
    appId: '1:904470300360:android:b418fab94b17e966f907fd',
    messagingSenderId: '904470300360',
    projectId: 'gerak-34866',
    storageBucket: 'gerak-34866.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAshpt6rVw8J92_ADxpTMtVsTxa22KEsI4',
    appId: '1:904470300360:ios:4ba89348e2e7f964f907fd',
    messagingSenderId: '904470300360',
    projectId: 'gerak-34866',
    storageBucket: 'gerak-34866.firebasestorage.app',
    androidClientId: '904470300360-8aiql1h0qgrajkgdk8uii8ic7045l4ac.apps.googleusercontent.com',
    iosClientId: '904470300360-4cbn1df6156ng2nnbm5jaafatmo751lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gerak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAshpt6rVw8J92_ADxpTMtVsTxa22KEsI4',
    appId: '1:904470300360:ios:4ba89348e2e7f964f907fd',
    messagingSenderId: '904470300360',
    projectId: 'gerak-34866',
    storageBucket: 'gerak-34866.firebasestorage.app',
    androidClientId: '904470300360-8aiql1h0qgrajkgdk8uii8ic7045l4ac.apps.googleusercontent.com',
    iosClientId: '904470300360-4cbn1df6156ng2nnbm5jaafatmo751lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gerak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0fFdANieqCpKUZQ7XEDFrl7-1dSjiigM',
    appId: '1:904470300360:web:e373b2a0e02d8ee1f907fd',
    messagingSenderId: '904470300360',
    projectId: 'gerak-34866',
    authDomain: 'gerak-34866.firebaseapp.com',
    storageBucket: 'gerak-34866.firebasestorage.app',
    measurementId: 'G-E2HT9WBW61',
  );

}